[functions]
  node_bundler = "esbuild"
  included_files = [
    "node_modules/@sparticuz/chromium/bin/**"
  ]
  external_node_modules = ["puppeteer-core", "@sparticuz/chromium"]

[functions."bot"]
  included_files = [
    "node_modules/puppeteer-core/**",
    "node_modules/@sparticuz/chromium/bin/**"
  ]