[build]
  command = "npm run build"
  functions = "src/netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."bot"]
  included_files = [
    "node_modules/puppeteer/.local-chromium/**",
    "/tmp/**"
  ]