[functions]
  node_bundler = "esbuild"
  external_node_modules = ["puppeteer-core", "@sparticuz/chromium"]

[functions."bot"]
  included_files = [
    "node_modules/puppeteer-core/**",
    "node_modules/@sparticuz/chromium/**",
    "/opt/buildhome/tmp/**"
  ]