[build]
  command = "TMPDIR=/opt/buildhome/tmp npm run build"
  functions = "dist/netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."bot"]
  included_files = [
    "node_modules/chrome-aws-lambda/**",
    "node_modules/puppeteer-core/**",
    "/opt/buildhome/tmp/**"
  ]
