[build]
  command = "npm run build"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."bot"]
  included_files = [
    "node_modules/chrome-aws-lambda/**",
    "node_modules/puppeteer-core/**",
    "/tmp/**"
  ]