[functions]
  node_bundler = "esbuild"
  included_files = [
    "node_modules/@sparticuz/chromium/bin/**"
  ]

[functions."bot"]
  included_files = [
    "node_modules/@sparticuz/chromium/bin/**"
  ]
